src/app_learning_logs/urls.py
#Define patrones para learnig_log
from django.urls import path
from . import views

app_name= 'app_learning_logs'
urlpatterns = [
    #Pagina de inicio
    path('', views.index, name = 'index'),
    #Pagina que muestra todos los temas
    path('topics/', views.topics, name='topics'),
    #Pagina de detalles sobre un tema individual
    path('topics/<int:topic_id>/', views.topic, name= 'topic'),
    #Pagina para añadir un tema nuevo
    path('new_topic/', views.new_topic, name='new_topic'),
    # Pagina para añadir una entrada nueva
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Pagina para editar una entrada
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
    #Pagina para borrar un topic
    path('delete_topic/<int:topic_id>/', views.delete_topic, name='delete_topic'),
    #Pagina para borrar una entrada
    path('delete_entry/<int:entry_id>/', views.delete_entry, name='delete_entry'),
    #Pagina que me dirige a acerca de mi
    path('acerca_de_mi/', views.acerca_de_mi, name='acerca_de_mi'),
    #PAgina que dirige a home
    path('home/', views.home, name='home'),
]

src/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('',include('app_learning_logs.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/users/urls.py
#Define patrones de URL para users.
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from .views import profile

app_name = 'users'
urlpatterns = [
    #Incluye url de autenticacion predeterminadas
    path('', include('django.contrib.auth.urls')),
    # Pagina de registro
    path('register/', views.register, name='register'),
    #Pagina de confirmacion de sesion cerrada
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    #Pagina de perfil
    path('profile/', views.profile, name='profile'),
]

src/app_learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
    #Un tema sobre el que esta aprendiendo el usuario
    text = models.CharField(max_length=50)
    image = models.ImageField(upload_to='topic_images/', null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        #Devuelve una representacion del modelo como cadena
        return self.text

class Entry(models.Model):
    #Algo especifico aprendido sobre un tema
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = "entries"

    def __str__(self): 
        #Devuelve una representacion del modelo como cadena
        return f"{self.text[:50]}"

src/app_learning_logs/forms.py
from django import forms 
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    image = forms.ImageField(required=False)

    class Meta:
        model = Topic
        fields = ["text", "image"]
        labels = {"text": "Título"}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['text'].widget.attrs.update({'placeholder': 'Ingresa el título aquí'})

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {"text" : ""}
        widgets = {"text": forms.Textarea(attrs={"cols": 80})}

src/app_learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import Http404
from .models import Topic, Entry
from .forms import TopicForm, EntryForm 


def index(request):
    #Pagina de inicio
    return render(request, "app_learning_logs/index.html")

@login_required
def home(request):
    #Pagina de inicio
    return render(request, "app_learning_logs/home.html")

@login_required
def topics(request):
    #Muestra todos los temas
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'app_learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    #Muestra un tema concreto y todas sus entradas
    topic = Topic.objects.get(id=topic_id)
    # Se asegura de que el tema pertenece al usuario actual
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render (request, 'app_learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            return redirect('app_learning_logs:topics')

        form = TopicForm(request.POST, request.FILES)  # Añade request.FILES para manejar la carga de archivos
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user

            # Guarda la imagen si se proporciona
            if 'image' in request.FILES:
                new_topic.image = request.FILES['image']

            new_topic.save()
            return redirect('app_learning_logs:topics')
    else:
        form = TopicForm()

    context = {'form': form}
    return render(request, 'app_learning_logs/new_topic.html', context)


@login_required
def delete_topic(request, topic_id):
    # Obtén el tema que se va a eliminar
    topic = get_object_or_404(Topic, id=topic_id)

    # Verifica si el usuario actual es el propietario del tema
    if request.user == topic.owner:
        # Elimina el tema
        topic.delete()
        return redirect('app_learning_logs:topics')  # Redirige a la lista de temas
    else:
        # Redirige a otra página si el usuario no es el propietario
        return redirect('app_learning_logs:topics')
    

@login_required
def new_entry(request, topic_id):
    # Añade una entrada nueva para un tema particular
    topic = Topic.objects.get(id=topic_id)

    if request.method == "POST":
        if 'cancel' in request.POST:
            # Si se presiona el botón de cancelar, redirige a otra página
            return redirect("otra_pagina")

        # Datos POST enviados; procesa los datos
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect("app_learning_logs:topic", topic_id=topic_id)
    else:
        # No se han enviado datos, crea un formulario en blanco
        form = EntryForm()

    # Muestra formulario en blanco o no válido
    context = {"topic": topic, "form": form}
    return render(request, "app_learning_logs/new_entry.html", context)

@login_required
def edit_entry(request, entry_id):
    # Obtiene la entrada existente que se va a editar según el ID proporcionado.
    entry = Entry.objects.get(id=entry_id)
    
    # Obtiene el tema asociado con la entrada.
    topic = entry.topic
    
    # Asegura que solo el usuario correcto pueda acceder a la edición de la entrada.
    if topic.owner != request.user:
        raise Http404
    
    if request.method == 'POST':
        # Datos POST enviados; procesa los datos del formulario.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            # Si el formulario es válido, guarda la entrada editada y redirige al detalle del tema.
            form.save()
            return redirect('app_learning_logs:topic', topic_id=topic.id)
    else:
        # Solicitud GET; prerrellena el formulario con la entrada actual.
        form = EntryForm(instance=entry)
    
    # Crea un contexto con la entrada, el tema y el formulario para pasar a la plantilla.
    context = {'entry': entry, 'topic': topic, 'form': form}
    
    return render(request, 'app_learning_logs/edit_entry.html', context)

@login_required
def delete_entry(request, entry_id):
    # Obtiene la entrada que se va a eliminar según el ID proporcionado.
    entry = get_object_or_404(Entry, id=entry_id)
    
    # Obtiene el tema asociado con la entrada.
    topic = entry.topic
    
    # Asegura que solo el usuario correcto pueda acceder a la eliminación de la entrada.
    if topic.owner != request.user:
        raise Http404
    
    if request.method == 'POST':
        # Confirma que la solicitud es mediante el método POST.
        entry.delete()
        return redirect('app_learning_logs:topic', topic_id=topic.id)
    
    # Si la solicitud no es mediante el método POST, renderiza el formulario de confirmación de eliminación.
    context = {'entry': entry, 'topic': topic}
    return render(request, 'app_learning_logs/topic', context)

def acerca_de_mi(request):
    return render(request, 'app_learning_logs/acerca_de_mi.html')

src/app_learning_logs/templates/app_learning_logs/acerca_de_mi.html
{% extends "app_learning_logs/base.html" %}
{% load static %}
{% block content %}
<div class="jumbotron" style="background: rgba(255, 255, 255, 0.075); text-align: center;">
    <img src="{% static 'images/FotoAcercademi.png' %}" alt="Leonel Romero" style="max-width: 200px; border-radius: 50%; margin-bottom: 20px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Acerca de mi</h2>
    <p class="lead text-white">
        ¡Hola!<br>
        Soy Leonel Romero, tengo 28 años, un profesional y estudiante con una sólida experiencia en campos fuera de la tecnología y desarrollo. Mi travesía en la programación comenzó en 2017, cuando estudié dos años de Analista de Sistemas. Durante ese tiempo, descubrí mi pasión por la codificación, una fascinación que nunca se apagó.

        A pesar de haber dejado la programación por compromisos laborales y personales, hoy estoy totalmente enfocado en alcanzar una de mis metas personales: trabajar y vivir de la programación. Mi dedicación y aprendizaje continuo me han llevado a embarcarme en este emocionante viaje.

        Fuera del mundo tecnológico me gusta, de viajar, conocer y entrenar, lo cual equilibra mi vida y me brinda perspectivas valiosas. Creo firmemente en la constancia y paciencia para hacer cosas significativas, que guían mi enfoque tanto en el trabajo como en la vida cotidiana.

        Estoy entusiasmado por lo que el futuro tiene reservado y comprometido a aprovechar al máximo cada oportunidad que se presente.

        <br><br>

        Puedes encontrarme en:
        <br>
        <a href="https://www.linkedin.com/in/leonel-romero/" target="_blank">LinkedIn</a> | <a href="https://github.com/rmleonel" target="_blank">GitHub</a>
    </p>
</div>

<div class="jumbotron" style="background: rgba(255, 255, 255, 0.075); text-align: center;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Acerca del proyecto</h2>
    <p class="lead text-white">
        Este proyecto surgió a partir de estudios, un proyecto final para CoderHouse y de los conocimientos adquiridos mientras exploraba un libro de Python, complementando mi aprendizaje más allá de los cursos tradicionales. Aunque es mi primer proyecto, pensé que sería una aplicación fácil de implementar.

        Como se detalla en el README, se trata de una aplicación web que funciona como un diario, permitiéndote agregar tus tópicos de estudio y registrar paso a paso con fechas. Además, ofrece la capacidad de editar y eliminar entradas, así como tópicos, siempre y cuando el usuario esté registrado.

        Aunque la aplicación es sencilla, ha requerido tiempo y dedicación para su desarrollo. En cuanto al diseño, mis conocimientos previos adquiridos durante un curso de front-end en 2020 facilitaron la aplicación de estilos y mejoras visuales.

        Espero sinceramente que encuentres la aplicación agradable y que cumpla con tus expectativas.
    </p>
</div>

{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,shrink-to-fit=no">
    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full '%}
    <style>
        body {
            position: relative;
            margin: 0;
            padding: 0;
            background: url('https://cdn.pixabay.com/photo/2017/08/06/22/11/people-2596896_1280.jpg') center center fixed; 
            background-size: cover;
        }
    
        body::before {
            content: "";
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background: inherit;
            background-size: cover;
            filter: blur(6px); 
            z-index: -1;
        }

        h1, h2, h3, h4, h5, h6, p {
            color: white;
        }
        
    </style>
    
</head>
<body class="bg-white" >
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4 border">
        {% block brand %}<a class="navbar-brand" href="{% url 'app_learning_logs:index' %}"> Learning Log </a>{% endblock brand %}
        <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_learning_logs:home' %}" style="font-size: 18px; margin-right: 24px;">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'app_learning_logs:topics' %}" style="font-size: 18px; margin-right: 24px;">Topics</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:profile' %}" style="font-size: 18px; margin-right: 24px;">Profile</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    {% if user.profile and user.profile.avatar %}
                        <span class="navbar-text mr-3">
                            <img src="{{ user.profile.avatar.url }}" alt="Avatar" style="width: 30px; height: 30px; border-radius: 50%; margin-right: 10px;">
                            Hola!, Bienvenido, {{ user.username }}
                        </span>
                    {% else %}
                        <span class="navbar-text mr-3">
                            Hola!, Bienvenido, {{ user.username }}
                        </span>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <!-- Formulario de cierre de sesión -->
                    <form method="post" action="{% url 'users:logout' %}" class="form-inline my-2 my-lg-0">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary my-2 my-sm-0 bg-info">Log out</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Registrarse</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
            {% endif %}
        </ul>
    </div>
    
    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    <footer class="footer mt-auto py-3 bg-dark" style="position: fixed; bottom: 0; width: 100%; background-color: #343a40; color: white; text-align: center;">
        <div class="container">
            <a href="{% url 'app_learning_logs:acerca_de_mi' %}" style="color: white; text-decoration: none;">Acerca de mi</a>
            <br> 
            <span class="text-muted">© 2024 Learning Log. Todos los derechos reservados.</span>
        </div>
    </footer>
    
</body>
</html>

src/app_learning_logs/templates/app_learning_logs/edit_entry.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block page_header %}
    <h2>Edit entry for <a href="{% url 'app_learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'app_learning_logs:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="btn btn-primary">Save changes</button>
        <a href="{% url 'app_learning_logs:topic' topic.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/home.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block content %}
<div class="jumbotron" style="background: rgba(255, 255, 255, 0.075); text-align: center; padding: 20px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Estrategias de estudio</h2>
</div>
<div class="jumbotron" style="background: rgba(0, 0, 0, 0.075); text-align: center;">
    <img src="https://cdn.pixabay.com/photo/2022/05/24/04/38/study-7217599_1280.jpg" alt="Descripción de la imagen" style="max-width: 25%; height: auto; margin-bottom: 20px; border-radius: 10px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Método Cornell </h2>
    <p class="lead text-white">
        Fue desarrollado por un docente de la Universidad de Cornell y se basa en optimizar la forma de cómo tomamos apuntes y organizamos notas en clases para luego estudiarlas.  
        Esta técnica se basa en dividir una hoja en tres secciones. Tras ello, podrás anotar las notas de clase, palabras clave y un resumen corto en los espacios distribuidos.  
        Este método de estudio es perfecto para que los estudiantes repasen de una manera más efectiva. Ahora, veremos más a fondo los espacios que dividimos: 
        Notas de clase: En esta parte coloca tus apuntes principales. Trata de que sean oraciones cortas en forma de lista o viñetas. Intenta empleando abreviaturas y ejemplos. Esta sección irá al lado derecho y es el espacio más grande de todos. 
        Palabras clave: Por lo general, se hace luego de que termines las notas de clase. Aquí puede ir las frases que consideres esenciales para entender mejor el tema. También es un espacio para colocar y plantear preguntas que te hagas. Este sector estará en la parte izquierda.
        Resumen corto: Consiste en anotar concretamente qué fue lo que aprendiste en la clase o lección. La acción de ir de reversa y sintetizar la información te ayudará muchísimo en tu proceso de aprendizaje. 
        Esta es una de las tantas técnicas para estudiar que puedes realizar cuando aprendes nuevos temas en clase, al momento de leer separatas, libros, recursos electrónicos o simplemente hacer un resumen conciso.  
    </p>
</div>
<div class="jumbotron" style="background: rgba(0, 0, 0, 0.075); text-align: center;">
    <img src="https://cdn.pixabay.com/photo/2019/07/11/14/24/reading-4330761_1280.jpg" alt="Descripción de la imagen" style="max-width: 25%; height: auto; margin-bottom: 20px; border-radius: 10px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Método Pomodoro </h2>
    <p class="lead text-white">
        Técnica basada en la concentración especial para las personas que tienden a distraerse mucho en sus redes sociales o páginas web mientras estudian. Su nombre proviene de los temporizadores de cocina en forma de tomate (pomodoro en italiano). 
        
        Consiste en destinar y distribuir tus tiempos para realizar una actividad como el estudio y concentrarte enteramente. Luego, tendremos un tiempo mucho menor en el que nos relajaremos y descansaremos. 
        
        Por ejemplo, puedes estudiar constantemente por 30 minutos y descansar 5. Los intervalos del método Pomodoro pueden variar dependiendo de la persona: de 35 a 7, 40 a 10 o 45 a 15 minutos.  
        
        Este método puede ser efectivo usando minuteros manuales, el temporizador de tu celular o aplicaciones especiales que te ayuden con esta técnica. A continuación, estas son las apps que pueden ayudarte: Forest, Focus To-Do, Brain Focus, Pomodoro Timer, entre otros. 
    </p>
</div>
<div class="jumbotron" style="background: rgba(8, 8, 8, 0.075); text-align: center;">
    <img src="https://cdn.pixabay.com/photo/2020/02/17/20/32/study-4857779_1280.jpg" alt="Descripción de la imagen" style="max-width: 25%; height: auto; margin-bottom: 20px; border-radius: 10px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Método de Mnemotecnias   </h2>
    <p class="lead text-white">
        Otra técnica que puede ser de gran utilidad es el uso de mnemotecnias para el aprendizaje. Esto se basa en aprender un concepto o palabras memorizando una determinada secuencia de frases, códigos, nombres, datos o números relacionados. 

        En algunos casos, hay mucha información que debemos retener, por lo que este método de estudio universitario y escolar nos ayudará con ese proceso. 

        Existe muchas formas de utilizar esta técnica, a continuación, las enlistamos: 

        Iniciales: consiste en juntar las primeras letras de las palabras que queremos memorizar y juntarlas en un simple concepto. No es necesario que tenga algún sentido, sino que funcione para nosotros. Por ejemplo, los gases nobles son el helio, neón, argón, kriptón, xenón, radón; pero si utilizamos solo la primera letra de cada palabra y le podemos poner RHANKX. Este sería nuestra mnemotecnia.  
        Historia: crearemos una historia en base a los conceptos que queramos recordar. Para este caso, queremos recordar las siguientes palabras: Francia, Revolución, 1789.  Entonces nuestra historia ficticia tendrá que utilizar esos conceptos. Por ejemplo: El otro día quería comprarme una cerveza marca Revolución. Al momento de pagar, me di cuenta de que no recordaba la clave de mi tarjeta. Al caminar por la plaza Francia me acordé de que mi contraseña era 1789. 
        Nubes mentales: se basa en asociar conceptos con las palabras que queremos recordar. No necesariamente debe haber una conexión lógica. Por ejemplo, quiero recordar los países Italia, Alemania y Holanda; así que los asociaré a los nombres propios de Ítala, Alejandria y Yolanda. De esa forma podremos recordar estos conceptos de manera más fácil.  
    </p>
</div>

<div class="jumbotron" style="background: rgba(5, 5, 5, 0.075); text-align: center;">
    <img src="https://cdn.pixabay.com/photo/2016/11/29/08/17/bible-1868359_1280.jpg" alt="Descripción de la imagen" style="max-width: 25%; height: auto; margin-bottom: 20px; border-radius: 10px;">
    <h2 class="display-4 text-light" style="font-weight: bold;">Escribir apuntes a mano </h2>
    <p class="lead text-white">
        Quizás suene algo obvio, pero escribir un nuevo aprendizaje manualmente en un papel pude ser uno de los ejemplos de métodos de estudio más grandes. 

        La virtualidad y la llegada del internet 4.0 nos ha llevado a automatizarnos; tanto es así que ahora preferimos usar nuestras laptops o libros electrónicos para tener cualquier apunte. 

        Lo cierto es que escribir a mano es una técnica clásica de estudio que te ayudará más de lo que crees. De acuerdo con un estudio publicado en la revista Psychological Science aprender a través de la escritura física es más beneficiosos que tecleando o simplemente observando.  

        “La escritura manual permite a las personas desarrollar una comprensión conceptual más sólida cuando se trata de procesar información”, explica el investigador Antonio Cantù, participante del mencionado estudio. 
    </p>
</div>

{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/index.html
{% extends "app_learning_logs/base.html" %}

{% block page_header %}
    <div class="jumbotron" style="background: rgba(255, 255, 255, 0.075); text-align: center;">
        <h1 class="display-2 text-succes" style="font-weight: bold; text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.5);" >Learning Log</h1>
        <p class="lead text-white">Cada vez que aprendas algo nuevo sobre un tema, escribe una entrada en la que resumas lo que has aprendido.</p>
        <a class="btn btn-lg btn-primary bg-info" href="{% url 'users:register' %}"
            role="button">Register &raquo;</a>
    </div>

    <div class="jumbotron" style="background: rgba(255, 255, 255, 0.075);">
        <h2 class="display-4 text-succes" style="font-weight: bold;" >Controla tu aprendizaje</h2>
        <p class="lead text-white">Es un sistema de diario en linea que le ayudara a llevar un registro de lo que ha aprendido sobre temas concretos.
        Explora, aprende y reflexiona con nuestro sistema de diario en línea. Registra tus conocimientos y descubrimientos sobre una variedad de temas concretos. 
        Este diario te brinda la libertad de agregar, editar y borrar tus entradas, permitiéndote personalizar y organizar tu experiencia de aprendizaje.</p>
    </div>
{% endblock page_header %}

src/app_learning_logs/templates/app_learning_logs/new_entry.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block page_header %}
    <h2>Add a new entry for <a href="{% url 'app_learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'app_learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit" class="btn btn-primary bg-info">Add entry</button>
        <a href="{% url 'app_learning_logs:topic' topic.id %}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/new_topic.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block page_header %}
    <h2>Agrega un nuevo topico aqui</h2>
{% endblock page_header %}

{% block content %}
<form action="{% url 'app_learning_logs:new_topic' %}" method="post" class="form" enctype="multipart/form-data">
    {% csrf_token %}

    <!-- Renderiza cada campo del formulario por separado -->
    <div class="form-group">
        <label for="{{ form.text.id_for_label }}">Título:</label>
        {{ form.text }}
    </div>

    <div class="form-group">
        <label for="{{ form.image.id_for_label }}">Imagen:</label>
        {{ form.image }}
    </div>

    <button name="submit" class="btn btn-primary bg-info">Agregar tema</button>
    <a href="{% url 'app_learning_logs:topics' %}" class="btn btn-secondary">Cancelar</a>
</form>
{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/topic.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block page_header %}
<h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
<p>
    <a href="{% url 'app_learning_logs:new_entry' topic.id %}" class="btn btn-primary bg-info">Agrega una nueva entrada</a>
</p>
{% for entry in entries %}
    <div class="card mb-3 bg-secondary">
        <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <div class="btn-group" role="group">
                <a href="{% url 'app_learning_logs:edit_entry' entry.id %}" class="btn btn-sm btn-primary bg-info"  style="margin-right: 20px;">Editar entrada</a>
                <form method="post" action="{% url 'app_learning_logs:delete_entry' entry_id=entry.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
            </div>
        </h4>
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>
{% empty %}
    <p>There are no entries for this topic yet.</p>
{% endfor %}
{% endblock content %}

src/app_learning_logs/templates/app_learning_logs/topics.html
{% extends "app_learning_logs/base.html" %}
{% block brand %}{% endblock brand %} 
{% block page_header %}
<h1>Topics</h1>
<h3>Esta es tu lista actualizada de topicos ingresados: </h3>
{% endblock page_header %}

{% block content %}
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    {% if topic.image %}
                        <img src="{{ topic.image.url }}" alt="Imagen del tema" style="max-width: 50px; max-height: 50px; margin-right: 10px;">
                    {% endif %}
                    <a href="{% url 'app_learning_logs:topic' topic.id %}" style="margin-right: 30px;">{{ topic }}</a>
                    <a href="{% url 'app_learning_logs:delete_topic' topic_id=topic.id %}" class="text-secondary small" style="font-size: small;">Delete topic</a>
                </h3>
            </li>
        {% empty %}
            <li><h3>No hay topicos agregados todavía</h3></li>
        {% endfor %}
    </ul>
    <a href="{% url 'app_learning_logs:new_topic' %}" class="btn btn-primary bg-info">Agrega un nuevo topico</a>
{% endblock content %}